### ISSUE TITLE
Problem RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:115

### ISSUE THREAD

**Issue by wenjun90** [thiagodma/Pytorch_exs#1]
Dear Thiago,

Thank you for your notebook.
I try run your notebook but there is a error like that:

**_RuntimeError                              Traceback (most recent call last)
<ipython-input-42-a34256b4db1b> in <module>()
----> 1 learn.fit_one_cycle(1)#, callbacks=[callbacks.SaveModelCallback(learn, every='improvement', monitor='valid_loss', name='stage-1')])

11 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2386         )
   2387     if dim == 2:
-> 2388         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   2389     elif dim == 4:
   2390         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:115_**

Could you show me how to solve this problem, please?

Thank you so much.

**Comment by thiagodma** [comment]
Hi @wenjun90 ! It seems like the code breaks with recent versions of Pytorch. I wrote a post about this notebook and one of the readers found that an image is breaking it. It seems like deleting image “61_3_20170109150557335.jpg” solves the problem. 

You may consider reading the [post](https://towardsdatascience.com/multi-task-learning-with-pytorch-and-fastai-6d10dc7ce855).

Please, let me know if deleting the image solved the problem.

**Comment by wenjun90** [comment]
Thank you so much @thiagodma 
I deleted that images and the problem is solved. :)
One question, in case I only want to predict gender and ethnicity, I will remove the rmse function?

**Comment by thiagodma** [comment]
If you want to predict only gender and ethnicity you should remove age from the dataset, remove one of the outputs of the neural network and remove the rmse function. If you only remove the rmse function it means that the model will not learn to predict age and you could just ignore the outputs for age.

That being said, I think that even if you want to predict only gender and ethnicity you should let the model learn to predict age. That's the beauty of multitask learning, learning to predict age may help the model to predict gender and ethnicity.
